name: hinerv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.4.0
      - annotated-types==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - deepspeed==0.16.3
      - einops==0.8.1
      - filelock==3.17.0
      - fsspec==2025.2.0
      - hjson==3.1.0
      - huggingface-hub==0.28.1
      - idna==3.10
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pillow==11.1.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytorch-msssim==1.0.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.5.2
      - sympy==1.13.1
      - timm==0.9.7
      - torch==2.6.0
      - torchac==0.9.3
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
